[server]
host: 0.0.0.0
port: 7125
klippy_uds_address: /home/ender/printer_data/comms/klippy.sock

[authorization]
trusted_clients:
    10.0.0.0/8
    127.0.0.0/8
    169.254.0.0/16
    172.16.0.0/12
    192.168.0.0/16
    FE80::/10
    ::1/128
cors_domains:
    *.lan
    *.local
    *.internal
    *://localhost
    *://localhost:*
    *://my.mainsail.xyz
    *://app.fluidd.xyz

[octoprint_compat]

[history]

[update_manager]
channel: dev
refresh_interval: 168

[update_manager mainsail]
path: /home/ender/mainsail
repo: mainsail-crew/mainsail
channel: stable
type: web
persistent_files:
    config.json

[update_manager mainsail-config]
managed_services: klipper
origin: https://github.com/mainsail-crew/mainsail-config.git
path: /home/ender/mainsail-config
primary_branch: master
type: git_repo

[update_manager moonraker-telegram-bot]
install_script: scripts/install.sh
requirements: scripts/requirements.txt
env: /home/ender/moonraker-telegram-bot-env/bin/python
origin: https://github.com/nlef/moonraker-telegram-bot.git
path: /home/ender/moonraker-telegram-bot
type: git_repo

[file_manager]
enable_object_processing: True
